# Generated by Django 5.1.1 on 2024-10-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="insert_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=250)),
                ("student_email", models.EmailField(max_length=254)),
                ("student_age", models.PositiveIntegerField(max_length=3)),
                ("gender", models.IntegerField(choices=[(0, "Male"), (1, "Female")])),
            ],
        ),
    ]
